### PR TITLE
Fixed Responsiveness of buttons

### PR DESCRIPTION
**Pull request by konavivekramakrishna**
This PR addresses the styling on the main page by adding media queries and also changes the Twitter logo.

Before : 

https://www.loom.com/share/c7c6fb1a612c445fa4a1da250122f60e?sid=c76da2ff-89a8-4fff-be2e-23a02e90d83f

After :

https://www.loom.com/share/8d4c5442b3a949e49bc374ca445bc189?sid=28e3821c-1142-43b6-aafd-06456b93c86a

### CODE REVIEW

**Comment by konavivekramakrishna** [comment]
@deneb-alpha 

could you please review

**Comment by konavivekramakrishna** [comment]
Before : 

image
image


After : 

image
image
image

**Comment by konavivekramakrishna** [comment]
Closing this PR and will open a new pull request with enhanced responsiveness in tablet view.

**Comment by deneb-alpha** [comment]
hi @konavivekramakrishna :) 

Before starting with the  implementation tasks,  we would like to classify  the work to be done and decide  in which direction to go. 

the implementation phase should  only start when also the GSoC project  will start

**Pull request closed without merging**
