### PR TITLE
Refactor CSS styles and update button design

### PR DESCRIPTION
**Pull request by codewithunknown**
This PR addresses the styling on the main page by adding media queries and also changes the Twitter logo.

Before : 

https://www.loom.com/share/c7c6fb1a612c445fa4a1da250122f60e?sid=c76da2ff-89a8-4fff-be2e-23a02e90d83f

After :

https://www.loom.com/share/8d4c5442b3a949e49bc374ca445bc189?sid=28e3821c-1142-43b6-aafd-06456b93c86a

### CODE REVIEW

**Comment by codewithunknown** [comment]
Before : 

image
image


After : 

image
image
image

**Comment by codewithunknown** [comment]
@deneb-alpha @raulillo82,

could you please review

**Comment by codewithunknown** [comment]
Hello @deneb-alpha 

Could you please review this PR and provide your suggestions? as part of increase accessibility and responsiveness under GSOC. I would like to contribute further. Can you please review this and provide your suggestions?

Looking forward to your feedback.

**Comment by deneb-alpha** [comment]
hi @codewithunknown 
as I mentioned in  the other  PR,  as  a  first step we wold  like to  collect the issues  and define  what  should  be fixed  and  how.  
There are several  small issues that should be addressed. we would like to classify them and have "the full picture".

the real fixes should be provided later, when the GSoC project implementation will start

**Comment by codewithunknown** [comment]
Hello @deneb-alpha 

Firstly, thank you for taking the time to review it. So, should I first collect the issues, determine the scope of improvement, define what should be fixed, and then create an issue?

**Comment by codewithunknown** [comment]
Regarding the implementation part and the approach to improving responsiveness and enhancing the UI, should I draft a proposal or simply file issues with possible ways of solving them and approaches?

**Comment by deneb-alpha** [comment]
> Regarding the implementation part and the approach to improving responsiveness and enhancing the UI, should I draft a proposal or simply file issues with possible ways of solving them and approaches?

I would suggest to open a GH issue per topic and refine into each of them the proposed approach to solve it.

**Comment by codewithunknown** [comment]
Got it, I will open GH issues per topic with possible to implement it

Thanks for the help @deneb-alpha

**Pull request closed without merging**
