### PR TITLE
Make home page responsive and fix element overlap issues

### LINKED ISSUE #91: Improve Uyuni website responsiveness across different devices
# Details

As part of [openSUSE/mentoring#205](https://github.com/openSUSE/mentoring/issues/205), this issue hopes to improve the responsiveness of Uyuni website.
The current Uyuni website is not responsive across different screen sizes, and this affects the experience of users accessing the site on mobile devices, tablets, and smaller desktop screens.
Also, this issue affects how screen readers interpret and read the website's content, as many elements overlap.
<br>
img1
img2

To fix this, we could add CSS media queries to adjust the layout and styling based on viewport size.

### PR DESCRIPTION
**Pull request by Rakielle**
## Details
This PR addresses the home page responsiveness on smaller screen

## Before

img1

## After

img2

Fixes #91

### CODE REVIEW

**Comment by deneb-alpha** [comment]
I was testing the change and  something improved, something  is still missing...

# Current


# with your changes:

**Review by deneb-alpha — CHANGES_REQUESTED** [review]
I'm  afraid but the changes on the Latest news section  looks broken to me. 
the  rendering is not good with the text that  is still cut off etc

**Comment by raulillo82** [comment]
I've just tested it locally.
At first, selecting a small device (mobile phone size) with either Firefox or Chrome in developer tools was showing something weird, see this in Firefox:

Captura de pantalla 2024-09-25 a las 14 29 06

and in Chrome:

_home_raul_Documentos_gh-repos_uyuni-project_uyuni-project github io_index html(iPhone SE)

But for Rachael it was fine. So I assumed the problem was my configuration of the developer tools, started a web server from the directory where I cloned Rachael's PR and opened it with my mobile. It is ok there, see:

```
raul@mordor:~/Documentos/gh-repos/uyuni-project/uyuni-project.github.io (master =)$ export LANG=C
raul@mordor:~/Documentos/gh-repos/uyuni-project/uyuni-project.github.io (master =)$ git checkout rachael/responsive-homepage 
Note: switching to 'rachael/responsive-homepage'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 16fa060 Make home page responsive and fix element overlap issues
raul@mordor:~/Documentos/gh-repos/uyuni-project/uyuni-project.github.io ((16fa060...))$ python3 -m http.server 8080
Serving HTTP on 0.0.0.0 port 8080 (http://0.0.0.0:8080/) ...
```

And the result looks fine to me:
uyuni-website_xiaomi_14

I'm approving this PR, but would appreciate a second review before merging.

**Review by raulillo82 — APPROVED** [review]
LGTM, but I'd prefer to have a second review.

**Comment by juliogonzalez** [comment]
> I'm afraid but the changes on the Latest news section looks broken to me. the rendering is not good with the text that is still cut off etc

I see something similar to marina:

imagen

Should the design be responsive regardless of the device used, just according to the size available?

I also see some empty spaces:

imagen

imagen

**Review by raulillo82 — CHANGES_REQUESTED** [review]
Rachael, please have a look at the comment from Julio. Even if I can see it well in a mobile phone, the fact that we both see weird things when using the dev-tools in the browser, or simply resizing the window, makes me suspicious. Or at least, we'll need to wait till Marina is back and we can have another opinion (she's out this week).

**Review by deneb-alpha — APPROVED** [review]
well done! it works now!

**Pull request merged**
